// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC7t83FxV6Vhe-9BqeCPoSzEGTJM7yUK8',
    appId: '1:161744072901:web:e83c949c6e685fce1880ac',
    messagingSenderId: '161744072901',
    projectId: 'chatapp-8a6a0',
    authDomain: 'chatapp-8a6a0.firebaseapp.com',
    storageBucket: 'chatapp-8a6a0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-kWv651aeh7mBDk4Z_sk7RvgUjdZqWV4',
    appId: '1:161744072901:android:1c12ac7d6f5cc9f81880ac',
    messagingSenderId: '161744072901',
    projectId: 'chatapp-8a6a0',
    storageBucket: 'chatapp-8a6a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiNyOWIzpdHKnkW0dHCTUUYYwYLQRiZ0U',
    appId: '1:161744072901:ios:e57294f509c334de1880ac',
    messagingSenderId: '161744072901',
    projectId: 'chatapp-8a6a0',
    storageBucket: 'chatapp-8a6a0.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiNyOWIzpdHKnkW0dHCTUUYYwYLQRiZ0U',
    appId: '1:161744072901:ios:e57294f509c334de1880ac',
    messagingSenderId: '161744072901',
    projectId: 'chatapp-8a6a0',
    storageBucket: 'chatapp-8a6a0.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCC7t83FxV6Vhe-9BqeCPoSzEGTJM7yUK8',
    appId: '1:161744072901:web:2a7be556a87691241880ac',
    messagingSenderId: '161744072901',
    projectId: 'chatapp-8a6a0',
    authDomain: 'chatapp-8a6a0.firebaseapp.com',
    storageBucket: 'chatapp-8a6a0.firebasestorage.app',
  );
}
